server.port=8960
server.servlet.context-path=/nrsm
spring.application.name=nrsm

spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/nrsm?useSSL=false&useUniCode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
spring.datasource.username=root
spring.datasource.password=metoo89745000

#Mybatis
mybatis.type-aliases-package=com.metoo.nrsm.core.mapper
mybatis.mapper-locations=classpath:./mapper/*.xml
task.switch.is-open=true

PYPATH=/opt/nrsm/py/